name: cb_demo

config-version: 2
version: '0.1'

profile: 'ods'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

   
seeds:
  +schema: seed


models:
  cb_demo:
    +as_columnstore: false

    cleansing:
      +schema: cleansing      

    for_bi:
      +schema: for_bi
      +materialized: table


tests:
  +store_failures: true  # all tests
  +schema: z_dbt_test_failures # With this config-Option , we tell dbt to store results of failed tests
                               # in a different schema. I want it to start with 'z', so the tables are
                               # listed at the end of the alphabetical table-listing in SSMS

