# example profiles.yml file
ods:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: cb_demo
      schema: dbo
      windows_login: False
      trust_cert: True
      user: dbt
      password: "123"