version: 2

models:
  - name: customer_howard
    description: for testing single row of top_10_customers
    columns:
      - name: customer_id
        description: This is a unique identifier for  customer howard
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_unique
    # tests: 
      # - dbt_expectations.expect_table_row_count_to_equal:
      #     value: 1
      ###### the test dbt_expectations.expect_table_row_count_to_equal does not work because
      ###### the compiled Query does something like "SELECT COUNT(*) = 1 AS Expression" which
      ###### doesnt work on SQL Server.
      ###### Need to write my own rowcount-check